- name: Install and configure firefox on debian
  become: true
  when: ansible_distribution == "Debian"
  block:
    - name: Install firefox-esr (debian)
      apt:
        install_recommends: no
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - firefox-esr
          - webext-ublock-origin-firefox

    - name: Install firefox-esr apparmor abstractions (debian)
      copy:
        src: ubuntu-browsers.d-firefox
        dest: /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox

    - name: Install firefox-esr apparmor profile (debian)
      copy:
        src: usr.bin.firefox-esr
        dest: /etc/apparmor.d/usr.bin.firefox-esr

    - name: Enforce firefox-esr apparmor profile (debian)
      command: aa-enforce usr.bin.firefox

    - name: Create firefox-esr policies directory (debian)
      file:
        path: /usr/lib/firefox-esr/distribution/
        state: directory

    - name: Copy firefox-esr policies (debian)
      copy:
        src: firefox-policies
        dest: /usr/lib/firefox-esr/distribution/policies.json

    - name: Add firefox user prefs (debian)
      copy:
        src: firefox-prefs
        dest: /etc/firefox-esr/all-prefs.js

- name: Install and configure firefox on Ubuntu
  when: ansible_distribution == "Ubuntu"
  become: yes
  block:
    - name: Install lxd snap
      community.general.snap:
        name:
          - firefox

    - name: touch firefox apparmor profile
      file:
        dest: /etc/apparmor.d/local/usr.bin.firefox
        state: touch

    - name: Add firefox user prefs (ubuntu)
      copy:
        src: firefox-prefs
        dest: /usr/lib/firefox/browser/defaults/preferences/all-prefs.js

    - name: Create firefox policies directory (ubuntu snap)
      file:
        path: /etc/firefox/policies
        state: directory

    - name: Copy firefox policies (ubuntu snap)
      copy:
        src: firefox-policies
        dest: /etc/firefox/policies/policies.json
