- name: Set Chromium as default browser
  command: update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/chromium 250
  become: yes
  tags: desktop

# See https://www.chromium.org/administrators/policy-list-3
- name: Create Chromium policies directory
  file:
    path: /etc/chromium/policies/managed
    state: directory
  become: yes
  tags: desktop

- name: Create Chromium JSON policy file
  template:
    src: chromium-policy
    dest: "/etc/chromium/policies/managed/my-policy.json"
  become: yes
  tags: desktop

- name: Create Chromium extensions directory
  file:
    path: /usr/share/chromium/extensions
    state: directory
  become: yes
  tags: desktop
