- name: Install chromium
  when: ansible_distribution == "Debian"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    pkg:
      - chromium

- name: Install chromium - ubuntu
  when: ansible_distribution == "Ubuntu"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    pkg:
      - chromium-browser

- name: Install ublock origin
  when: ansible_distribution == "Debian"
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    pkg:
      - webext-ublock-origin-chromium

- name: Set Chromium as default browser
  when: ansible_distribution == "Debian"
  command: update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/chromium 250
  become: yes

- name: Set Chromium as default browser
  when: ansible_distribution == "Ubuntu"
  command: update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/chromium-browser 250
  become: yes

# See https://www.chromium.org/administrators/policy-list-3
- name: Create Chromium policies directory
  file:
    path: /etc/chromium/policies/managed
    state: directory
  become: yes

- name: Create Chromium JSON policy file
  template:
    src: chromium-policy
    dest: "/etc/chromium/policies/managed/my-policy.json"
  become: yes

- name: Create Chromium extensions directory
  file:
    path: /usr/share/chromium/extensions
    state: directory
  become: yes

- name: Create Chromium JSON policy file
  copy:
    src: imwheelrc
    dest: ~/.imwheelrc
  become: yes
