- name: Install common packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    pkg:
      - cockpit
      - cockpit-machines
      - cockpit-podman

- name: enable and start cockpit service
  become: yes
  ansible.builtin.systemd:
    name: cockpit
    state: started
    enabled: yes
