---
- hosts: localhost
  connection: local
  roles:
    - common
    - python
    - ufw
    - badhosts
    - emacs
    - mongo
    - cockpit
    - bookmarks

    - desktop
    - fonts
    - chromium
    - firefox
    - kitty

    - go
    - nim
    - rust
    - nodejs

    - koreader
    - calibre

    - kubectl
    - k9s
    - lazydocker
