---
- hosts: localhost
  connection: local
  roles:
    - common
    - python
    - ufw
    - badhosts
    - emacs
    - mongo
    - bookmarks
    - desktop
    - fonts
    - chromium
    - nim
    - koreader
