---
- hosts: localhost
  connection: local

  tasks:
    - name: Install etckeeper
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - etckeeper

    - name: etckeeper commit
      become: true
      command: etckeeper commit "pre-ansible auto-commit"
      ignore_errors: yes

    - name: add contrib and non-free repos (debian)
      when: ansible_distribution == "Debian"
      become: true
      replace:
        dest: /etc/apt/sources.list
        regexp: '^(deb.+)(?<! contrib non-free)$'
        replace: '\1 contrib non-free'
      register: add_repos

    - name: update cache after adding repos (debian)
      when: ansible_distribution == "Debian" and add_repos.changed
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 0

    - name: Install common packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - jq
          - build-essential
          - python3-pip
          - rsync
          - git
          - tmux
          - htop
          - iotop
          - bmon
          - powertop
          - lsof
          - imagemagick
          - ncdu
          - aria2
          - autoconf
          - automake
          - bzip2
          - fzf
          - g++
          - emacs-nox
          - lnav
          - oathtool
          - p7zip
          - parallel
          - rdate
          - sqlite3
          - syncthing
          - tig
          - unace
          - unar
          - unrar
          - unzip
          - valgrind
          - tshark
          - zip
          - apt-file
          - autojump
          - bc
          - clamav
          - cloc
          - cmake
          - cmake-curses-gui
          - curl
          - dict-gcide
          - dictd
          - ranger
          - smartmontools
          - lshw
          - m4
          - mutt
          - openvpn
          - tinc
          - pwgen
          - sshfs
          - strace
          - tree
          - ufw
          - w3m
          - lynx
          - wget
          - whois
          - xdg-user-dirs
          - xz-utils
          - screenfetch
          - net-tools
          - aptitude
          - tlp
          - apparmor
          - apparmor-utils
          - apparmor-profiles
          - apparmor-profiles-extra
          - snapd

    - name: Install lxd snap
      become: yes
      community.general.snap:
        name:
          - lxd

    - name: Install python dev packages
      pip:
        name:
          - python-lsp-server
          - isort
          - black

    - name: accept ms font eula (have not actually read it)
      become: true
      debconf:
        name: ttf-mscorefonts-installer
        question: msttcorefonts/accepted-mscorefonts-eula
        vtype: boolean
        value: true
      tags: desktop

    - name: Install Xorg and i3
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - i3
          - i3blocks
          - i3lock
          - xserver-xorg
          - xserver-xorg-input-all
          - xserver-xorg-input-synaptics
          - xserver-xorg-video-all
          - xinit
          - x11-apps
          - x11-utils
          - x11-xkb-utils
          - x11-xserver-utils
          - xterm
          - elementary-xfce-icon-theme
          - libglib2.0-bin
          - xclip
          - webp
          - fonts-dejavu
          - fonts-firacode
          - fonts-ubuntu
          - fonts-ubuntu-console
          - fonts-roboto
          - xfonts-terminus
          - ttf-mscorefonts-installer
      tags:
        - desktop

    - name: Install lightdm
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - lightdm
          - lightdm-gtk-greeter
      tags: desktop

    - name: Install desktop packages
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - feh
          - mpv
          - zathura
          - zathura-djvu
          - gimp
          - kitty
          - thunderbird
          - wireshark
          - thunar
          - mousepad
          - rawtherapee
          - cups
          - fbreader
          - lxappearance
          - gthumb
          - obs-studio
          - remmina
          - scrot
          - sunclock
          - virt-manager
          - transmission-remote-gtk
          - blueman
          - syncthing-gtk
          - gparted
          - gnome-disk-utility
      tags:
        - desktop

    - name: Install firefox-esr (debian)
      when: ansible_distribution == "Debian"
      become: true
      apt:
        install_recommends: no
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - firefox-esr
      tags:
        - desktop

    - name: Install firefox-esr apparmor abstractions (debian)
      when: ansible_distribution == "Debian"
      become: true
      copy:
        src: ubuntu-browsers.d-firefox
        dest: /etc/apparmor.d/abstractions/ubuntu-browsers.d/firefox
      tags:
        - desktop

    - name: touch emacs custom config file
      become: yes
      file:
        dest: /etc/apparmor.d/local/usr.bin.firefox
        state: touch

    - name: Install firefox-esr apparmor profile (debian)
      when: ansible_distribution == "Debian"
      become: true
      copy:
        src: usr.bin.firefox-esr
        dest: /etc/apparmor.d/usr.bin.firefox-esr
      tags:
        - desktop

    - name: Enforce firefox-esr apparmor profile (debian)
      when: ansible_distribution == "Debian"
      become: true
      command: aa-enforce usr.bin.firefox

    - name: Install firefox (ubuntu)
      when: ansible_distribution == "Ubuntu"
      become: true
      apt:
        install_recommends: no
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - firefox
      tags:
        - desktop

    - name: Copy desktop background
      become: yes
      copy:
        src: desktop_background.png
        dest: /usr/local/share/desktop_background.png
      tags:
        - desktop

    - name: Set login screen background
      become: yes
      community.general.alternatives:
        name: desktop-login-background
        path: /usr/local/share/desktop_background.png
      tags:
        - desktop
      ignore_errors: yes

    - name: Install desktop packages (no recommends)
      become: true
      apt:
        install_recommends: no
        update_cache: yes
        cache_valid_time: 36000
        state: latest
        pkg:
          - barrier
          - libreoffice
          - webext-ublock-origin-firefox
      tags:
        - desktop
      ignore_errors: yes

    - name: Remove avahi-daemon, gdm3, etc
      become: true
      apt:
        state: absent
        pkg:
          - avahi-daemon
          - gdm3
          - command-not-found
          - motd-news-config

    - name: Download jetbrains font
      ansible.builtin.get_url:
        url: https://github.com/JetBrains/JetBrainsMono/releases/download/v2.242/JetBrainsMono-2.242.zip
        dest: /tmp/JetBrainsMono.zip
        checksum: sha256:4e315b4ef176ce7ffc971b14997bdc8f646e3d1e5b913d1ecba3a3b10b4a1a9f
      tags:
        - desktop

    - name: Create font directory
      file:
        path: ~/.fonts
        state: directory
      tags:
        - desktop

    - name: Extract jetbrains font
      ansible.builtin.unarchive:
        src: /tmp/JetBrainsMono.zip
        dest: ~/.fonts
      tags:
        - desktop

    - name: Create emacs directory
      file:
        path: ~/.emacs.d
        state: directory

    - name: Copy emacs config
      copy:
        src: emacs-config
        dest: ~/.emacs.d/init.el

    - name: touch emacs custom config file
      file:
        dest: ~/.emacs.d/custom.el
        state: touch
        mode: u+rw,g-wx,o-rwx

    - name: Create i3 config directory
      file:
        path: ~/.config/i3
        state: directory
      tags:
        - desktop

    - name: Copy i3 config
      template:
        src: i3-config
        dest: ~/.config/i3/config
      tags:
        - desktop

    - name: Copy desktop setup script
      copy:
        src: start.sh
        dest: ~/start.sh
      tags:
        - desktop

    - name: Create kitty config directory
      file:
        path: ~/.config/kitty
        state: directory
      tags:
        - desktop

    - name: Copy kitty config
      template:
        src: kitty-config
        dest: ~/.config/kitty/kitty.conf
      tags:
        - desktop

    - name: Copy kitty theme
      copy:
        src: kitty-theme
        dest: ~/.config/kitty/current-theme.conf
      tags:
        - desktop

    - name: Create firefox-esr policies directory (debian)
      when: ansible_distribution == "Debian"
      become: true
      file:
        path: /usr/lib/firefox-esr/distribution/
        state: directory
      tags:
        - desktop

    - name: Copy firefox-esr policies (debian)
      when: ansible_distribution == "Debian"
      become: true
      copy:
        src: firefox-policies
        dest: /usr/lib/firefox-esr/distribution/policies.json
      tags:
        - desktop

    - name: Add firefox user prefs (debian)
      when: ansible_distribution == "Debian"
      become: true
      copy:
        src: firefox-prefs
        dest: /etc/firefox-esr/all-prefs.js
      tags:
        - desktop

    - name: Add firefox user prefs (ubuntu)
      when: ansible_distribution == "Ubuntu"
      become: true
      copy:
        src: firefox-prefs
        dest: /usr/lib/firefox/browser/defaults/preferences/all-prefs.js
      tags:
        - desktop

    - name: Create firefox policies directory (ubuntu deb)
      when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int < 22
      become: true
      file:
        path: /usr/lib/firefox/distribution/
        state: directory
      tags:
        - desktop

    - name: Copy firefox policies (ubuntu deb)
      when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int < 22
      become: true
      copy:
        src: firefox-policies
        dest: /usr/lib/firefox/distribution/policies.json
      tags:
        - desktop

    - name: Create firefox policies directory (ubuntu snap)
      when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int >= 22
      become: true
      file:
        path: /etc/firefox/policies
        state: directory
      tags:
        - desktop

    - name: Copy firefox policies (ubuntu snap)
      when: ansible_distribution == "Ubuntu" and ansible_lsb.major_release|int >= 22
      become: true
      copy:
        src: firefox-policies
        dest: /etc/firefox/policies/policies.json
      tags:
        - desktop

    - name: Copy gtk2 config
      template:
        src: gtk2-config
        dest: ~/.gtkrc-2.0
      tags:
        - desktop

    - name: Create gtk3 config directory
      file:
        path: ~/.config/gtk-3.0
        state: directory
      tags:
        - desktop

    - name: Copy gtk3 config
      template:
        src: gtk3-config
        dest: ~/.config/gtk-3.0/settings.ini
      tags:
        - desktop

    - name: Enable firewall
      community.general.ufw:
        state: enabled
        direction: incoming
        policy: deny
      become: true
      tags:
        - desktop

    - name: Set firewall logging
      community.general.ufw:
        logging: 'on'
      become: true
      tags:
        - desktop

    - name: download adware+malware hosts file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
        dest: /tmp/hosts
      tags:
        - desktop

    - name: download mozilla hosts file
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/MrRawes/firefox-hosts/firefox-hosts/hosts
        dest: /tmp/mozilla-hosts
      tags:
        - desktop

    - name: insert hostname into /tmp/hosts
      blockinfile:
        path: /tmp/hosts
        block: |
          # block mozilla telemetry
          {{ lookup('file', '/tmp/mozilla-hosts') }}
          # add localhost
          127.0.1.1 {{ ansible_hostname }}
      become: true
      tags:
        - desktop

    - name: copy adware+malware hosts file to /etc/hosts
      copy:
        src: /tmp/hosts
        dest: /etc/hosts
      become: true
      tags:
        - desktop

    - name: Create command logs directory
      file:
        path: ~/.logs
        state: directory

    - name: Setup bashrc
      blockinfile:
        path: ~/.bashrc
        block: |
          . /usr/share/autojump/autojump.sh
          HISTTIMEFORMAT="%F %T "
          shopt -s histappend
          HISTSIZE=100000
          HISTFILESIZE=200000
          export PROMPT_COMMAND='if [ "$(id -u)" -ne 0 ]; then echo "$(date "+%Y-%m-%d.%H:%M:%S") $(pwd) $(history 1)" >> ~/.logs/bash-history-$(date "+%Y-%m-%d").log; fi'
          PATH=$PATH:/snap/bin

    - name: setup Xresources (user)
      template:
        src: xresources
        dest: ~/.Xresources
      tags:
        - desktop

    - name: check if /etc/X11/Xresources directory exists
      stat:
        path: /etc/X11/Xresources
      register: x11dir
      tags:
        - desktop

    - name: delete global Xresources directory
      file:
        path: /etc/X11/XResources
        state: absent
      when: x11dir.stat.exists and x11dir.stat.isdir
      tags:
        - desktop

    - name: setup Xresources (global)
      template:
        src: xresources
        dest: /etc/X11/Xresources
      become: yes
      tags:
        - desktop

    - name: Create xorg.conf.d directory
      become: yes
      file:
        path: /etc/X11/xorg.conf.d
        state: directory
      tags:
        - desktop

    - name: setup x11 synaptics
      copy:
        src: synaptics-config
        dest: /etc/X11/xorg.conf.d/70-synaptics.conf
      become: yes
      tags:
        - desktop

    - name: setup X11 dpi in lightdm
      template:
        src: lightdm-config
        dest: /etc/lightdm/lightdm.conf
      become: yes
      tags:
        - desktop

    - name: hide user images in lightdm-gtk-greeter
      community.general.ini_file:
        path: /etc/lightdm/lightdm-gtk-greeter.conf
        section: greeter
        option: hide-user-image
        value: "true"
      become: yes
      tags:
        - desktop

    - name: remove panel from lightdm-gtk-greeter
      community.general.ini_file:
        path: /etc/lightdm/lightdm-gtk-greeter.conf
        section: greeter
        option: indicators
        value: ""
      become: yes
      tags:
        - desktop

    - name: setup git
      copy:
        src: git-config
        dest: ~/.gitconfig

    - name: set gsettings key theme to emacs
      command: gsettings set org.gnome.desktop.interface gtk-key-theme "Emacs"
      tags:
        - desktop

    - name: add autologin group
      when: lookup('env', 'AUTOLOGIN')|bool
      become: yes
      group:
        name: autologin
        state: present

    - name: add user to autologin group
      when: lookup('env', 'AUTOLOGIN')|bool
      become: yes
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: autologin
        append: yes

    - name: add user to other groups
      become: yes
      user:
        name: "{{ lookup('env', 'USER') }}"
        groups: "{{ item }}"
        append: yes
      loop:
        - lpadmin
        - libvirt
        - lxd

    - name: Create mpv config directory
      file:
        path: ~/.config/mpv
        state: directory
      tags:
        - desktop

    - name: Create mpv screenshot directory
      file:
        path: ~/mpv-screenshots
        state: directory
      tags:
        - desktop

    - name: copy mpv config
      copy:
        src: mpv-config
        dest: ~/.config/mpv/mpv.conf
