---
- hosts: localhost
  connection: local
  roles:
    - common
    - python
    - ufw
    - badhosts
    - emacs
    - mongo
    - cockpit
    - bookmarks

    - desktop
    - fonts
    - chromium
    - kitty

    - go
    - nim
    - rust
    - nodejs

    - koreader

    - kubectl
    - k9s
    - lazydocker
