---
- hosts: localhost
  connection: local
  roles:
    - common
    - ufw
    - badhosts
    - emacs
    - mongo
    - cockpit

    - desktop
    - chromium
    - firefox
    - kitty

    - go
    - nim
    - rust
    - nodejs

    - koreader
    - calibre

    - minikube
