- name: download adware+malware hosts file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/StevenBlack/hosts/master/alternates/fakenews-gambling-porn-social/hosts
    dest: /opt/tmp/hosts

- name: download mozilla hosts file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/MrRawes/firefox-hosts/firefox-hosts/hosts
    dest: /opt/tmp/mozilla-hosts

- name: download crypto hosts file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/hosts.txt
    dest: /opt/tmp/crypto-hosts

- name: insert hostname into /opt/tmp/hosts
  blockinfile:
    path: /opt/tmp/hosts
    block: |
      127.0.1.1 cdn.matomo.cloud
      # block mozilla telemetry
      {{ lookup('file', '/opt/tmp/mozilla-hosts') }}
      # block crypto hosts
      {{ lookup('file', '/opt/tmp/crypto-hosts') }}
      # add localhost
      127.0.1.1 {{ ansible_hostname }}
  become: true

- name: copy adware+malware hosts file to /etc/hosts
  copy:
    src: /opt/tmp/hosts
    dest: /etc/hosts
  become: true
