- name: Download Calibre
  get_url:
    url: https://github.com/kovidgoyal/calibre/releases/download/v6.3.0/calibre-6.3.0-x86_64.txz
    dest: /opt/tmp/calibre-6.3.0-x86_64.txz
    checksum: sha256:2aa596827c09a20793d2639f392ea202c9dba8251295712b8655a53a7d5ae6d9
  tags: desktop

- name: Create calibre directory
  file:
    path: /opt/calibre6.3.0
    state: directory
  become: yes
  tags: desktop

- name: Extract calibre to /opt
  become: yes
  ansible.builtin.unarchive:
    src: /opt/tmp/calibre-6.3.0-x86_64.txz
    dest: /opt/calibre6.3.0
