- name: Download Calibre
  get_url:
    url: https://github.com/kovidgoyal/calibre/releases/download/v6.5.0/calibre-6.5.0-x86_64.txz
    dest: /opt/tmp/calibre-6.5.0-x86_64.txz
    checksum: sha256:b82678fc41efa9365d9f227646561b1ec8f6490ef67b2126ce3d5750df105e0e

- name: Create calibre directory
  file:
    path: /opt/calibre6.5.0
    state: directory
  become: yes

- name: Extract calibre to /opt
  become: yes
  ansible.builtin.unarchive:
    src: /opt/tmp/calibre-6.5.0-x86_64.txz
    dest: /opt/calibre6.5.0
