- name: Download Calibre
  get_url:
    url: https://github.com/kovidgoyal/calibre/releases/download/v6.4.0/calibre-6.4.0-x86_64.txz
    dest: /opt/tmp/calibre-6.4.0-x86_64.txz
    checksum: sha256:6e0f624d27b62296450aa0037e34fe755f095565bb853c9925b09fd71820c5a2

- name: Create calibre directory
  file:
    path: /opt/calibre6.4.0
    state: directory
  become: yes

- name: Extract calibre to /opt
  become: yes
  ansible.builtin.unarchive:
    src: /opt/tmp/calibre-6.4.0-x86_64.txz
    dest: /opt/calibre6.4.0
