- name: Install common packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    pkg:
      - python-is-python3
      - build-essential
      - python3-pip
      - python3-virtualenv
      - python3-watchdog

      - mypy

- name: Install python dev packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    name:
      - python3-pylsp
      - python3-pylsp-black
      - python3-pylsp-jsonrpc
      - black
      - python3-pylsp-black
      - python3-isort
      - mypy
      - python3-mypy
      - python3-mypy-extensions
      - python3-flake8
      - python3-rope

- name: copy flake8 config
  copy:
    src: flake8-config
    dest: ~/.config/flake8
