- name: Download kitty
  ansible.builtin.get_url:
    url: https://github.com/kovidgoyal/kitty/releases/download/v0.26.1/kitty-0.26.1-x86_64.txz
    dest: /opt/tmp/kitty-0.26.1-x86_64.txz
    checksum: sha256:2b1b54383ba85c067723e5f8bf6fd7d460172905aeb8464d345ed89d2d132c91

- name: Create kitty directory
  become: yes
  file:
    path: /opt/kitty
    state: directory

- name: Extract kitty to /opt/kitty
  become: yes
  ansible.builtin.unarchive:
    src: /opt/tmp/kitty-0.26.1-x86_64.txz
    dest: /opt/kitty

- name: Create kitty config directory
  file:
    path: ~/.config/kitty
    state: directory

- name: Copy kitty config
  template:
    src: kitty-config
    dest: ~/.config/kitty/kitty.conf

- name: Copy kitty theme
  copy:
    src: kitty-theme
    dest: ~/.config/kitty/current-theme.conf
