- name: Install emacs-nox
  become: true
  when: '"all" not in ansible_run_tags and "desktop" not in ansible_run_tags'
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    pkg:
      - emacs-nox

- name: Install emacs
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    pkg:
      - emacs

- name: Create emacs directory
  file:
    path: ~/.emacs.d
    state: directory

- name: Create emacs cache directory
  file:
    path: ~/.emacs.d/.cache
    state: directory

- name: Copy treemacs persist file if it doesn't exist
  copy:
    src: treemacs-persist
    dest: ~/.emacs.d/.cache/treemacs-persist
    force: no

- name: Copy emacs config
  copy:
    src: emacs-config
    dest: ~/.emacs.d/init.el


- name: touch emacs custom config file
  file:
    dest: ~/.emacs.d/custom.el
    state: touch
    mode: u+rw,g-wx,o-rwx
