- name: Download go
  ansible.builtin.get_url:
    url: https://go.dev/dl/go1.19.linux-amd64.tar.gz
    dest: /opt/tmp/go1.19.linux-amd64.tar.gz
    checksum: sha256:464b6b66591f6cf055bc5df90a9750bf5fbc9d038722bb84a9d56a2bea974be6

- name: Extract go to /opt
  become: yes
  ansible.builtin.unarchive:
    src: /opt/tmp/go1.19.linux-amd64.tar.gz
    dest: /opt
