- name: accept ms font eula (have not actually read it)
  become: true
  debconf:
    name: ttf-mscorefonts-installer
    question: msttcorefonts/accepted-mscorefonts-eula
    vtype: boolean
    value: true

- name: Install Xorg and i3
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 36000
    state: latest
    pkg:
      - fonts-dejavu
      - fonts-firacode
      - fonts-ubuntu
      - fonts-ubuntu-console
      - fonts-roboto
      - xfonts-terminus
      - ttf-mscorefonts-installer

- name: Download jetbrains font
  ansible.builtin.get_url:
    url: https://github.com/JetBrains/JetBrainsMono/releases/download/v2.242/JetBrainsMono-2.242.zip
    dest: /opt/tmp/JetBrainsMono.zip
    checksum: sha256:4e315b4ef176ce7ffc971b14997bdc8f646e3d1e5b913d1ecba3a3b10b4a1a9f

- name: Download scientifica font
  ansible.builtin.get_url:
    url: https://github.com/nerdypepper/scientifica/releases/download/v2.3/scientifica.tar
    dest: /opt/tmp/scientifica.tar
    checksum: sha256:f0857869a0e846c6f175dcb853dd1f119ea17a75218e63b7f0736d5a8e1e8a7f

- name: Create font directory
  file:
    path: ~/.fonts
    state: directory

- name: Extract jetbrains font
  ansible.builtin.unarchive:
    src: /opt/tmp/JetBrainsMono.zip
    dest: ~/.fonts

- name: Extract scientifica font
  ansible.builtin.unarchive:
    src: /opt/tmp/scientifica.tar
    dest: ~/.fonts

- name: Copy scientifica fontconfig
  become: true
  copy:
    src: 91-scientifica.conf
    dest: /etc/fonts/conf.d/91-scientifica.conf
